---

- name: Install nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Backup default config
  copy: remote_src=True src="/etc/nginx/{{ item }}" dest="/etc/nginx/{{ item }}.bak"
  with_items:
      - nginx.conf

- name: Copy nginx.conf
  template:
    src: templates/{{ item }}.j2
    dest: /etc/nginx/{{ item }}
    mode: 0644
  notify: restart nginx
  with_items:
    - nginx.conf
    - secure.conf
    - common.conf
    - proxy.conf
#    - sites-available/machet-einfa.ch.conf
    - sites-available/cloud.conf

- name: Disable all sites
  file:
    state: absent
    path: "/etc/nginx/sites-enabled"

- name: Recreate sites-enabled
  file:
    state: directory
    path: "/etc/nginx/sites-enabled"


- name: Enable sites
  file: remote_src=True src="/etc/nginx/sites-available/{{ item }}"
              dest="/etc/nginx/sites-enabled/{{ item }}"
              state=link
  with_items:
    # - machet-einfa.ch.conf
    - cloud.conf

- name: Ensure nginx cache
  file:
    path: /var/cache/nginx
    owner: root
    group: root
    state: directory
    mode: 0755

- name: Ensure web directory is owned by www-data
  file:
    path: /var/www
    owner: www-data
    group: www-data
    state: directory
    mode: 0775

- name: Remove default nginx site config
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx

# - name: Generate dhparam file
#   # -dsaparm => https://goo.gl/OkbDqi for faster generation
#   command: openssl dhparam -dsaparam -out /etc/ssl/certs/dhparam.pem 4096 creates=/etc/ssl/certs/dhparam.pem
