---

- name: Install oh-my-zsh
  shell: 'sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"'
  tags: bash

- name: copy omz theme
  copy:
    src: "templates/acrolyt.zsh-theme"
    dest: /root/.oh-my-zsh/themes/acrolyt.zsh-theme
  tags: bash

- name: copy dotfiles
  copy:
    src: "templates/{{ item }}"
    dest: "/root/{{ item }}"
  with_items:
    - ".bashrc"
    - ".bash_profile"
    - ".zshrc"
  tags: bash

