---

- name: Create letsencrypt certificates with certbot
  hosts: all
  become: yes

  vars_prompt:

    - name: domains
      prompt: Domain(s), comma-separated without spaces
      private: no

  tasks:

    - name: Create certificate for {{ domains }}
      command: certbot certonly \
        --nginx \
        --non-interactive \
        --agree-tos \
        --email {{ letsencrypt_email }} \
        --domains {{ domains }}
