version: "2.1"

volumes:
  mysql:
  mailserver:

services:

  web:
    container_name: acrolyt-web
    image: nginx:1.13.3-alpine
    depends_on:
      - app
#      - node
    volumes:
      - ./docker/assets/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    volumes_from:
      - app
    ports:
      - 8080:80

  db:
    container_name: acrolyt-db
    image: mysql
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: v092135
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD-dev}
      MYSQL_USER: ${MYSQL_USER-dev}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD-dev}
    ports:
      - 127.0.0.1:3306:3306
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 10s
      retries: 5

  php-myadmin:
    container_name: acrolyt-phpmyadmin
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - 127.0.0.1:8080:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: ${MYSQL_USER-dev}
      PMA_PASSWORD: ${MYSQL_PASSWORD-dev}

  mailsserver:
    container_name: acrolyt-mail
    image: tvial/docker-mailserver:latest
    hostname: mail
    domainname: domain.com
    container_name: mail
    ports:
    - "25:25"
    - "143:143"
    - "587:587"
    - "993:993"
    volumes:
    - maildata:/var/mail
    - mailstate:/var/mail-state
    - ./config/:/tmp/docker-mailserver/
    environment:
    - ENABLE_SPAMASSASSIN=1
    - ENABLE_CLAMAV=1
    - ENABLE_FAIL2BAN=1
    - ENABLE_POSTGREY=1
    - ONE_DIR=1
    - DMS_DEBUG=0
    cap_add:
    - NET_ADMIN

    volumes:
      maildata:
        driver: local
      mailstate:
        driver: local

#  node:
#    container_name: acrolyt-node
#    image: gitlab.bytenetz.de:4567/bytepark/docker-images/node:8-alpine
#    depends_on:
#      redis:
#        condition: service_started
#    volumes:
#      - ./data/node:/dock
#    working_dir: /dock
#    ports:
#      - 127.0.0.1:5000:5000
#    command: yarn run dev
