---

- name: Bootstrap server
  hosts: all
  become: yes

  roles:
    - role: bootstrap
      tags: bootstrap

    - role: bash
      tags: bash

#    - role: nginx
#      tags: nginx

    - role: letsencrypt
      tags: letsencrypt

    - role: webfolders
      tags: webfolders

    - role: docker
      tags: docker


#    - role: php
#      tags: php
#
#    - role: mysql
#      tags: mysql
#
#    - role: phpmyadmin
#      tags: phpmyadmin
#
#    - role: mailserver
#      tags: mailserver