---

- name: Ensure docker dependencies
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - python-pip

- name: Ensure offical apt docker key
  apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg

- name: Ensure official apt docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"

- name: Install docker community edition
  package:
    name: docker-ce
    state: present

- name: Install docker-compose
  pip:
    name: docker-compose

- name: Copy docker-compose files
  template:
    src: "templates/docker-compose.yml.j2"
    dest: "/home/{{ user_login }}/{{ docker_webfolder }}/docker-compose.yml"
  tags: docker-copy

- name: Create config folders
  file:
    path: /home/{{ user_login }}/{{ item }}
    state: directory
    mode: 0750
  with_items:
    - "{{ docker_webfolder }}/www"
    - "{{ docker_webfolder }}/configs"
    - "{{ docker_webfolder }}/configs/nginx"
    - "{{ docker_webfolder }}/configs/letsencrypt"
    - "{{ docker_webfolder }}/mysql"
    - "{{ docker_webfolder }}/nextclouddb"
    - "{{ docker_webfolder }}/docker"
    - "{{ docker_webfolder }}/docker/nextcloud/data"
    - "{{ docker_webfolder }}/docker/nextcloud/config"
    - "{{ docker_webfolder }}/docker/nextcloud/apps"
    - "{{ docker_webfolder }}/docker/nextcloud/themes"

- name: Move config files
  copy:
    src: "templates/{{ item.from }}/"
    dest: "/home/{{ user_login }}/{{ docker_webfolder }}/{{ item.to }}"
  with_items:
    - { from: 'sslproxy/cloudproxy.conf', to: '/configs/nginx/default.conf' }
  tags: docker-reverse-proxy

- name: Run docker
  # shell: "cd /home/{{  user_login }}/{{ docker_webfolder }} && docker-compose stop {{ item }} && docker-compose up -d {{ item }}"
  shell: "cd /home/{{ user_login }}/{{ docker_webfolder }} && docker-compose stop && docker-compose up -d"
  with_items:
    - nextcloud
  tags: docker-restart